// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Obstacles.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_DRONESIM_OBSTACLES_H_
#define _FAST_DDS_GENERATED_DRONESIM_OBSTACLES_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Obstacles_SOURCE)
#define Obstacles_DllAPI __declspec( dllexport )
#else
#define Obstacles_DllAPI __declspec( dllimport )
#endif // Obstacles_SOURCE
#else
#define Obstacles_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Obstacles_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace DroneSim {
    /*!
     * @brief This class represents the structure Obstacles defined by the user in the IDL file.
     * @ingroup OBSTACLES
     */
    class Obstacles
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport Obstacles();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~Obstacles();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object DroneSim::Obstacles that will be copied.
         */
        eProsima_user_DllExport Obstacles(
                const Obstacles& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object DroneSim::Obstacles that will be copied.
         */
        eProsima_user_DllExport Obstacles(
                Obstacles&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object DroneSim::Obstacles that will be copied.
         */
        eProsima_user_DllExport Obstacles& operator =(
                const Obstacles& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object DroneSim::Obstacles that will be copied.
         */
        eProsima_user_DllExport Obstacles& operator =(
                Obstacles&& x);

        /*!
         * @brief Comparison operator.
         * @param x DroneSim::Obstacles object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const Obstacles& x) const;

        /*!
         * @brief Comparison operator.
         * @param x DroneSim::Obstacles object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const Obstacles& x) const;

        /*!
         * @brief This function copies the value in member obstacles_x
         * @param _obstacles_x New value to be copied in member obstacles_x
         */
        eProsima_user_DllExport void obstacles_x(
                const std::vector<int32_t>& _obstacles_x);

        /*!
         * @brief This function moves the value in member obstacles_x
         * @param _obstacles_x New value to be moved in member obstacles_x
         */
        eProsima_user_DllExport void obstacles_x(
                std::vector<int32_t>&& _obstacles_x);

        /*!
         * @brief This function returns a constant reference to member obstacles_x
         * @return Constant reference to member obstacles_x
         */
        eProsima_user_DllExport const std::vector<int32_t>& obstacles_x() const;

        /*!
         * @brief This function returns a reference to member obstacles_x
         * @return Reference to member obstacles_x
         */
        eProsima_user_DllExport std::vector<int32_t>& obstacles_x();
        /*!
         * @brief This function copies the value in member obstacles_y
         * @param _obstacles_y New value to be copied in member obstacles_y
         */
        eProsima_user_DllExport void obstacles_y(
                const std::vector<int32_t>& _obstacles_y);

        /*!
         * @brief This function moves the value in member obstacles_y
         * @param _obstacles_y New value to be moved in member obstacles_y
         */
        eProsima_user_DllExport void obstacles_y(
                std::vector<int32_t>&& _obstacles_y);

        /*!
         * @brief This function returns a constant reference to member obstacles_y
         * @return Constant reference to member obstacles_y
         */
        eProsima_user_DllExport const std::vector<int32_t>& obstacles_y() const;

        /*!
         * @brief This function returns a reference to member obstacles_y
         * @return Reference to member obstacles_y
         */
        eProsima_user_DllExport std::vector<int32_t>& obstacles_y();
        /*!
         * @brief This function sets a value in member obstacles_number
         * @param _obstacles_number New value for member obstacles_number
         */
        eProsima_user_DllExport void obstacles_number(
                int32_t _obstacles_number);

        /*!
         * @brief This function returns the value of member obstacles_number
         * @return Value of member obstacles_number
         */
        eProsima_user_DllExport int32_t obstacles_number() const;

        /*!
         * @brief This function returns a reference to member obstacles_number
         * @return Reference to member obstacles_number
         */
        eProsima_user_DllExport int32_t& obstacles_number();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const DroneSim::Obstacles& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        std::vector<int32_t> m_obstacles_x;
        std::vector<int32_t> m_obstacles_y;
        int32_t m_obstacles_number;
    };
} // namespace DroneSim

#endif // _FAST_DDS_GENERATED_DRONESIM_OBSTACLES_H_