// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Obstacles.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Obstacles.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

DroneSim::Obstacles::Obstacles()
{
    // m_obstacles_x com.eprosima.idl.parser.typecode.SequenceTypeCode@17211155

    // m_obstacles_y com.eprosima.idl.parser.typecode.SequenceTypeCode@b3d7190

    // m_obstacles_number com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5fdba6f9
    m_obstacles_number = 0;

}

DroneSim::Obstacles::~Obstacles()
{


}

DroneSim::Obstacles::Obstacles(
        const Obstacles& x)
{
    m_obstacles_x = x.m_obstacles_x;
    m_obstacles_y = x.m_obstacles_y;
    m_obstacles_number = x.m_obstacles_number;
}

DroneSim::Obstacles::Obstacles(
        Obstacles&& x)
{
    m_obstacles_x = std::move(x.m_obstacles_x);
    m_obstacles_y = std::move(x.m_obstacles_y);
    m_obstacles_number = x.m_obstacles_number;
}

DroneSim::Obstacles& DroneSim::Obstacles::operator =(
        const Obstacles& x)
{

    m_obstacles_x = x.m_obstacles_x;
    m_obstacles_y = x.m_obstacles_y;
    m_obstacles_number = x.m_obstacles_number;

    return *this;
}

DroneSim::Obstacles& DroneSim::Obstacles::operator =(
        Obstacles&& x)
{

    m_obstacles_x = std::move(x.m_obstacles_x);
    m_obstacles_y = std::move(x.m_obstacles_y);
    m_obstacles_number = x.m_obstacles_number;

    return *this;
}

bool DroneSim::Obstacles::operator ==(
        const Obstacles& x) const
{

    return (m_obstacles_x == x.m_obstacles_x && m_obstacles_y == x.m_obstacles_y && m_obstacles_number == x.m_obstacles_number);
}

bool DroneSim::Obstacles::operator !=(
        const Obstacles& x) const
{
    return !(*this == x);
}

size_t DroneSim::Obstacles::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t DroneSim::Obstacles::getCdrSerializedSize(
        const DroneSim::Obstacles& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.obstacles_x().size() > 0)
    {
        current_alignment += (data.obstacles_x().size() * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.obstacles_y().size() > 0)
    {
        current_alignment += (data.obstacles_y().size() * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void DroneSim::Obstacles::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_obstacles_x;
    scdr << m_obstacles_y;
    scdr << m_obstacles_number;

}

void DroneSim::Obstacles::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_obstacles_x;
    dcdr >> m_obstacles_y;
    dcdr >> m_obstacles_number;
}

/*!
 * @brief This function copies the value in member obstacles_x
 * @param _obstacles_x New value to be copied in member obstacles_x
 */
void DroneSim::Obstacles::obstacles_x(
        const std::vector<int32_t>& _obstacles_x)
{
    m_obstacles_x = _obstacles_x;
}

/*!
 * @brief This function moves the value in member obstacles_x
 * @param _obstacles_x New value to be moved in member obstacles_x
 */
void DroneSim::Obstacles::obstacles_x(
        std::vector<int32_t>&& _obstacles_x)
{
    m_obstacles_x = std::move(_obstacles_x);
}

/*!
 * @brief This function returns a constant reference to member obstacles_x
 * @return Constant reference to member obstacles_x
 */
const std::vector<int32_t>& DroneSim::Obstacles::obstacles_x() const
{
    return m_obstacles_x;
}

/*!
 * @brief This function returns a reference to member obstacles_x
 * @return Reference to member obstacles_x
 */
std::vector<int32_t>& DroneSim::Obstacles::obstacles_x()
{
    return m_obstacles_x;
}
/*!
 * @brief This function copies the value in member obstacles_y
 * @param _obstacles_y New value to be copied in member obstacles_y
 */
void DroneSim::Obstacles::obstacles_y(
        const std::vector<int32_t>& _obstacles_y)
{
    m_obstacles_y = _obstacles_y;
}

/*!
 * @brief This function moves the value in member obstacles_y
 * @param _obstacles_y New value to be moved in member obstacles_y
 */
void DroneSim::Obstacles::obstacles_y(
        std::vector<int32_t>&& _obstacles_y)
{
    m_obstacles_y = std::move(_obstacles_y);
}

/*!
 * @brief This function returns a constant reference to member obstacles_y
 * @return Constant reference to member obstacles_y
 */
const std::vector<int32_t>& DroneSim::Obstacles::obstacles_y() const
{
    return m_obstacles_y;
}

/*!
 * @brief This function returns a reference to member obstacles_y
 * @return Reference to member obstacles_y
 */
std::vector<int32_t>& DroneSim::Obstacles::obstacles_y()
{
    return m_obstacles_y;
}
/*!
 * @brief This function sets a value in member obstacles_number
 * @param _obstacles_number New value for member obstacles_number
 */
void DroneSim::Obstacles::obstacles_number(
        int32_t _obstacles_number)
{
    m_obstacles_number = _obstacles_number;
}

/*!
 * @brief This function returns the value of member obstacles_number
 * @return Value of member obstacles_number
 */
int32_t DroneSim::Obstacles::obstacles_number() const
{
    return m_obstacles_number;
}

/*!
 * @brief This function returns a reference to member obstacles_number
 * @return Reference to member obstacles_number
 */
int32_t& DroneSim::Obstacles::obstacles_number()
{
    return m_obstacles_number;
}


size_t DroneSim::Obstacles::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool DroneSim::Obstacles::isKeyDefined()
{
    return false;
}

void DroneSim::Obstacles::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}

